
def getFiles(iteration,nTuple, inDir = "hists", year="2015",syst=""):

    files = {"H260": inDir+"/NWS_m260"+syst+"/hists.root",
             "H270": inDir+"/NWS_m270"+syst+"/hists.root",
             "H280": inDir+"/NWS_m280"+syst+"/hists.root",
             "H290": inDir+"/NWS_m290"+syst+"/hists.root",
             "H300": inDir+"/NWS_m300"+syst+"/hists.root",
             "H400": inDir+"/NWS_m400"+syst+"/hists.root",
             "H500": inDir+"/NWS_m500"+syst+"/hists.root",
             "H600": inDir+"/NWS_m600"+syst+"/hists.root",
             "H700": inDir+"/NWS_m700"+syst+"/hists.root",
             "H800": inDir+"/NWS_m800"+syst+"/hists.root",
             "H900": inDir+"/NWS_m900"+syst+"/hists.root",
             "H1000": inDir+"/NWS_m1000"+syst+"/hists.root",
             "H1100": inDir+"/NWS_m1100"+syst+"/hists.root",
             "H1200": inDir+"/NWS_m1200"+syst+"/hists.root",
             "N400": inDir+"/NWS_NLO_m400"+syst+"/hists.root",
             "N500": inDir+"/NWS_NLO_m500"+syst+"/hists.root",
             "N600": inDir+"/NWS_NLO_m600"+syst+"/hists.root",
             "N700": inDir+"/NWS_NLO_m700"+syst+"/hists.root",
             "N800": inDir+"/NWS_NLO_m800"+syst+"/hists.root",
             "N900": inDir+"/NWS_NLO_m900"+syst+"/hists.root",
             "N1000": inDir+"/NWS_NLO_m1000"+syst+"/hists.root",
             "M260": inDir+"/RSG_c10_m260"+syst+"/hists.root",
             "M270": inDir+"/RSG_c10_m270"+syst+"/hists.root",
             "M280": inDir+"/RSG_c10_m280"+syst+"/hists.root",
             "M290": inDir+"/RSG_c10_m290"+syst+"/hists.root",
             "M300": inDir+"/RSG_c10_m300"+syst+"/hists.root",
             "M400": inDir+"/RSG_c10_m400"+syst+"/hists.root",
             "M500": inDir+"/RSG_c10_m500"+syst+"/hists.root",
             "M600": inDir+"/RSG_c10_m600"+syst+"/hists.root",
             "M700": inDir+"/RSG_c10_m700"+syst+"/hists.root",
             "M800": inDir+"/RSG_c10_m800"+syst+"/hists.root",
             "M900": inDir+"/RSG_c10_m900"+syst+"/hists.root",
             "M1000": inDir+"/RSG_c10_m1000"+syst+"/hists.root",
             "M1100": inDir+"/RSG_c10_m1100"+syst+"/hists.root",
             "M1200": inDir+"/RSG_c10_m1200"+syst+"/hists.root",
             "R260": inDir+"/RSG_c20_m260"+syst+"/hists.root",
             "R270": inDir+"/RSG_c20_m270"+syst+"/hists.root",
             "R280": inDir+"/RSG_c20_m280"+syst+"/hists.root",
             "R290": inDir+"/RSG_c20_m290"+syst+"/hists.root",
             "R300": inDir+"/RSG_c20_m300"+syst+"/hists.root",
             "R400": inDir+"/RSG_c20_m400"+syst+"/hists.root",
             "R500": inDir+"/RSG_c20_m500"+syst+"/hists.root",
             "R600": inDir+"/RSG_c20_m600"+syst+"/hists.root",
             "R700": inDir+"/RSG_c20_m700"+syst+"/hists.root",
             "R800": inDir+"/RSG_c20_m800"+syst+"/hists.root",
             "R900": inDir+"/RSG_c20_m900"+syst+"/hists.root",
             "R1000": inDir+"/RSG_c20_m1000"+syst+"/hists.root",
             "R1100": inDir+"/RSG_c20_m1100"+syst+"/hists.root",
             "R1200": inDir+"/RSG_c20_m1200"+syst+"/hists.root",
             "N1N1_m130": inDir+"/N1N1_m130"+syst+"/hists.root",
             "N1N1_m300": inDir+"/N1N1_m300"+syst+"/hists.root",
             "BBS_m500": inDir+"/BBS_m500"+syst+"/hists.root",
             "BBS_m800": inDir+"/BBS_m800"+syst+"/hists.root",
             "nonResonant": inDir+"/SMNR"+syst+"/hists.root",
             "SMNR": inDir+"/SMNR"+syst+"/hists.root",
             "SMNR_MhhWeight": inDir+"/SMNR_MhhWeight"+syst+"/hists.root",
             "SMNR_MhhWeight_PUWeight": inDir+"/SMNR_MhhWeight_PUWeight"+syst+"/hists.root",
             "trigger": inDir+"/efficiencies_acceptances.root",
             "data": inDir+"/data_iter"+iteration+"/hists.root",
             "qcd" : inDir+"/qcd_iter"+iteration+"/hists.root",
             "ttbarShape":inDir+"/ttbar_shape_iter"+iteration+"/hists.root",
             "allhadShape":inDir+"/allhad_shape_iter"+iteration+"/hists.root",
             "nonallhadShape":inDir+"/nonallhad_shape_iter"+iteration+"/hists.root",
             "zbb": inDir+"/zbb/hists.root",
             "ttbar":inDir+"/ttbar_iter"+iteration+"/hists.root",
             "allhad":inDir+"/allhad_iter"+iteration+"/hists.root",
             "nonallhad":inDir+"/nonallhad_iter"+iteration+"/hists.root",
             "ZHad":inDir+"/ZHad_iter"+iteration+"/hists.root",
             "weights": "XhhResolved/data/weights2bto4b_"+year+"_Nominal"+str(int(iteration)+1)+".root",
             "LimitSettingInputs": "LimitSettingInputs/resolved_4bSR_"+year+".root",
             "fitCrossChecks": "StatAnalysis/Code/betterFitPlots.root",
             #qcd cross checks
             }

    return files
